image: ruby:2.5.1
services:
  - postgres:9.5
before_script:
  - apt-get update -qq && apt-get install -y -qq postgresql postgresql-contrib libpq-dev cmake
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --without staging production
variables:
  POSTGRES_DB: astapor_test
  POSTGRES_USER: astapor
  POSTGRES_PASSWORD: astapor
  DB_HOST: postgres
stages:
  - build
  - deploy

job_build:
  stage: build
  script:
    - RACK_ENV=test bundle exec rake

job_deploy:
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=astapor-api --api-key=1eef7d7f-9679-4f40-8ce4-49b1bea812f2
  only:
    - master