require: rubocop-rspec

# Avoid methods longer than 30 lines of code
MethodLength:
  Max: 30
Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Max: 10
Metrics/BlockLength:
  Max: 25
  ExcludedMethods: ['controllers', 'describe', 'context' ]
Metrics/LineLength:
  Max: 100
  IgnoredPatterns: ['(When|Given|Then)', '(get|post|put)']
Naming/PredicateName:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Documentation:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
RSpec/ExampleWording:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/HookArgument:
  EnforcedStyle: each
RSpec/MessageSpies:
  EnforcedStyle: receive
RSpec/MultipleExpectations:
  Max: 10
Metrics/AbcSize:
  Max: 25



